test:
  sessions:
    default:
      database: mongoid_delorean_test
      hosts:
        - localhost:27017
      options:
        max_retries: 1
        retry_interval: 0
#        safe: true
#        consistency: :strong
